const http = require('http');
const fs = require('fs');
const path = require('path');

const PORT = 5000;
const DIST_DIR = path.resolve(__dirname, '..', 'dist');

const MIME_TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.map': 'application/json',
};

function resolveHtmlFile(pathname) {
  if (pathname === '/' || pathname === '') {
    return path.join(DIST_DIR, 'index.html');
  }

  // Check exact html match
  const directHtml = path.join(DIST_DIR, `${pathname}.html`);
  if (fs.existsSync(directHtml) && fs.statSync(directHtml).isFile()) {
    return directHtml;
  }

  // Check index.html inside directory
  const nestedIndex = path.join(DIST_DIR, pathname, 'index.html');
  if (fs.existsSync(nestedIndex) && fs.statSync(nestedIndex).isFile()) {
    return nestedIndex;
  }

  // Dynamic route patterns generated by expo export
  if (/^\/learn\/[^/]+\/[^/]+$/.test(pathname)) {
    return path.join(DIST_DIR, 'learn', '[eventId]', '[subtopicId].html');
  }
  if (/^\/heritage-voices\/article\/[^/]+$/.test(pathname)) {
    return path.join(DIST_DIR, 'heritage-voices', 'article', '[id].html');
  }
  if (/^\/heritage-voices\/author\/[^/]+$/.test(pathname)) {
    return path.join(DIST_DIR, 'heritage-voices', 'author', '[id].html');
  }
  if (/^\/game\/chronosearch\/[^/]+$/.test(pathname)) {
    return path.join(DIST_DIR, 'game', 'chronosearch', '[puzzleId].html');
  }
  if (/^\/decade\/[^/]+$/.test(pathname)) {
    return path.join(DIST_DIR, 'decade', '[id].html');
  }
  if (/^\/civilization\/[^/]+$/.test(pathname)) {
    return path.join(DIST_DIR, 'civilization', '[id].html');
  }
  if (/^\/experience\/[^/]+$/.test(pathname)) {
    return path.join(DIST_DIR, 'experience', '[id].html');
  }
  if (/^\/period\/[^/]+$/.test(pathname)) {
    return path.join(DIST_DIR, 'period', '[id].html');
  }
  if (/^\/topic\/[^/]+$/.test(pathname)) {
    return path.join(DIST_DIR, 'topic', '[id].html');
  }
  if (/^\/game\/[^/]+$/.test(pathname)) {
    const gameIdHtml = path.join(DIST_DIR, 'game', '[id].html');
    if (fs.existsSync(gameIdHtml)) return gameIdHtml;
  }

  // Fallback to index.html for SPA
  return path.join(DIST_DIR, 'index.html');
}

const server = http.createServer((req, res) => {
  const urlObj = new URL(req.url, `http://${req.headers.host || 'localhost'}`);
  let pathname = decodeURIComponent(urlObj.pathname);

  // 1. Direct static file check
  const filePath = path.join(DIST_DIR, pathname);
  if (fs.existsSync(filePath) && fs.statSync(filePath).isFile()) {
    const ext = path.extname(filePath).toLowerCase();
    const contentType = MIME_TYPES[ext] || 'application/octet-stream';
    res.writeHead(200, { 'Content-Type': contentType });
    return fs.createReadStream(filePath).pipe(res);
  }

  // 2. HTML route resolution
  const htmlFile = resolveHtmlFile(pathname);
  if (fs.existsSync(htmlFile) && fs.statSync(htmlFile).isFile()) {
    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
    return fs.createReadStream(htmlFile).pipe(res);
  }

  // 3. Fallback
  res.writeHead(404, { 'Content-Type': 'text/plain' });
  res.end('Not Found');
});

server.listen(PORT, '0.0.0.0', () => {
  console.log(`Akhyana Production Web Server listening at http://localhost:${PORT}`);
});
